#
# This file contains configuration flags to customize your site
#

lang: "en"
url: https://blogtester2.github.io

title: Best Chairs
description: Find the best chairs for your home.

logo: https://i.postimg.cc/y6prxp9P/chair-logo.png
favicon: https://i.ibb.co/BKqmkBj/chair-192.png
avatar: https://i.ibb.co/BKqmkBj/chair-192.png

contact:
  phone: "(844) 890-789"
  email: "support@bestchairs.com"
  address: "150 Harrison Ave, Kearny, NJ 07032, United States"
  facebook: "https://facebook.com/BestChairs"
  google: "https://businesses.google.com/BestChairs"
  twitter: "https://twitter.com/BestChairs"
  instagram: "https://instagram.com/BestChairs"
  yelp: "https://yelp.com/BestChairs"

footer:
  description: "Best Chairs helps you to find the best chairs for your home or office. Browse our online store or visit our showrooms."
  benefits:
    - "Range of high quality chairs"
    - "100+ positive reviews"
    - "Free shipping"
    - "2 year warranty"

# 
# You don't need to change any of the configuration flags below
# 

baseurl: ""

timezone: null

excerpt_separator: <!--more-->

permalink: pretty

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

paginate: 5
paginate_path: "/blog/page:num/"

collections:
  posts:
    output: true
    permalink: /blog/:title/
  products:
    _hide_content: false
    output: true
  stores:
    _hide_content: false
    output: true

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  - webrick
  - jekyll-github-metadata

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
